[discord]
token = "<YOUR_TOKEN_HERE>"
comm_channel = 0
guilds = [0]

[graphql]
ws_url = "wss://dev-api.mensatt.de/data/graphql"
https_url = "https://dev-api.mensatt.de/data/graphql"

[mensatt]
occurrence_url = "https://mensatt.de/details/"
user = "<username>"
password = "<password>"
jwt_threshold_secs = 120

[image]
image_url = "https://api.mensatt.de/content/image/"
rotate_url = "https://api.mensatt.de/content/rotate"
key = "<key>"
